return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"clojure",
			"comment",
			"csv",
			"diff",
			"dockerfile",
			"ebnf",
			"editorconfig",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gotmpl",
			"gowork",
			"http",
			"ini",
			"jq",
			"json",
			"json5",
			"linkerscript",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"passwd",
			"pem",
			"powershell",
			"printf",
			"properties",
			"proto",
			"python",
			"regex",
			"ruby",
			"rust",
			"sql",
			"ssh_config",
			"starlark",
			"templ",
			"terraform",
			"tmux",
			"toml",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zig",
		},
		sync_install = false,
		auto_install = true,
		indent = {
			enable = true,
		},
		highlight = {
			enable = true,
		},
	},
	config = function(_, opts) 
		require('nvim-treesitter.install').prefer_git = true
		require('nvim-treesitter.configs').setup(opts)
	end
}
